import argparse
import joblib
import pandas as pd
import glob
import os
import sys
import warnings

# The exact 54 features the models were trained on
FEATURE_COLUMNS = [
    'input_size', 'is_cold_start', 'platform_azure', 'platform_google', 
    'runtime_nodejs', 'runtime_python', 'region_us-central1', 'region_us-east-1', 
    'workload_cpu_math_2_xs_v1', 'workload_cpu_math_3_xs_v1', 'workload_cpu_math_4_xs_v1', 
    'workload_cpu_math_5_xs_v1', 'workload_crypto_1_xs_v1', 'workload_crypto_2_xs_v1', 
    'workload_crypto_3_xs_v1', 'workload_crypto_4_xs_v1', 'workload_crypto_5_xs_v1', 
    'workload_crypto_hash_xs_v1', 'workload_data_proc_1_xs_v1', 'workload_data_proc_2_xs_v1', 
    'workload_data_proc_3_xs_v1', 'workload_data_proc_4_xs_v1', 'workload_data_proc_5_xs_v1', 
    'workload_disk_io_1_xs_v1', 'workload_disk_io_2_xs_v1', 'workload_disk_io_3_xs_v1', 
    'workload_disk_io_4_xs_v1', 'workload_disk_io_5_xs_v1', 'workload_fibonacci_xs_v1', 
    'workload_file_io_xs_v1', 'workload_float_ops_xs_v1', 'workload_json_transform_xs_v1', 
    'workload_matrix_mult_xs_v1', 'workload_mem_alloc_1_xs_v1', 'workload_mem_alloc_2_xs_v1', 
    'workload_mem_alloc_3_xs_v1', 'workload_mem_dict_5_xs_v1', 'workload_mem_string_4_xs_v1', 
    'workload_net_sim_1_xs_v1', 'workload_net_sim_2_xs_v1', 'workload_net_sim_3_xs_v1', 
    'workload_net_sim_4_xs_v1', 'workload_net_sim_5_xs_v1', 'workload_prime_sieve_xs_v1', 
    'workload_sci_1_xs_v1', 'workload_sci_2_xs_v1', 'workload_sci_3_xs_v1', 'workload_sci_4_xs_v1', 
    'workload_sci_5_xs_v1', 'workload_web_biz_1_xs_v1', 'workload_web_biz_2_xs_v1', 
    'workload_web_biz_3_xs_v1', 'workload_web_biz_4_xs_v1', 'workload_web_biz_5_xs_v1'
]

def load_models(models_dir):
    """Automatically finds and loads the best models generated by train_models.py"""
    duration_models = glob.glob(os.path.join(models_dir, 'best_duration_model_*.pkl'))
    cost_models = glob.glob(os.path.join(models_dir, 'best_cost_model_*.pkl'))
    
    if not duration_models or not cost_models:
        print(f"Error: Could not find trained models in {models_dir}.")
        print("Please run `python models/train_models.py` first to generate the models.")
        sys.exit(1)
        
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        duration_model = joblib.load(duration_models[0])
        cost_model = joblib.load(cost_models[0])
    
    # Extract model names for display
    d_name = os.path.basename(duration_models[0]).replace('best_duration_model_', '').replace('.pkl', '')
    c_name = os.path.basename(cost_models[0]).replace('best_cost_model_', '').replace('.pkl', '')
    
    return duration_model, cost_model, d_name, c_name

def create_feature_vector(platform, runtime, region, cold_start, input_size, workload):
    """Creates a 54-column DataFrame feature vector for the ML model."""
    features = {col: 0 for col in FEATURE_COLUMNS}
    
    features['input_size'] = input_size
    features['is_cold_start'] = 1 if cold_start else 0
    
    if platform == 'azure':
        features['platform_azure'] = 1
    elif platform == 'gcp':
        features['platform_google'] = 1
        
    if runtime == 'python':
        features['runtime_python'] = 1
    elif runtime == 'nodejs':
        features['runtime_nodejs'] = 1
        
    if region == 'us-central1':
        features['region_us-central1'] = 1
    elif region == 'us-east-1':
        features['region_us-east-1'] = 1
        
    workload_col = f"workload_{workload}"
    if workload_col in features:
        features[workload_col] = 1
    else:
        print(f"  Warning: Workload '{workload}' not found in training data. Using default baseline.")
        
    return pd.DataFrame([features])

def analyze_project(path):
    """Heuristically analyze a script file or project directory to guess runtime and workload."""
    code_text = ""
    py_count = 0
    js_count = 0
    
    if os.path.isfile(path):
        files = [path]
    else:
        files = []
        for root, dirs, fnames in os.walk(path):
            if any(ignore in root for ignore in ['.git', 'node_modules', 'venv', '__pycache__', 'env']):
                continue
            for f in fnames:
                if f.endswith('.py') or f.endswith('.js'):
                    files.append(os.path.join(root, f))
                    
    for f in files:
        ext = os.path.splitext(f)[1].lower()
        if ext == '.py': py_count += 1
        elif ext == '.js': js_count += 1
        
        try:
            with open(f, 'r', encoding='utf-8') as file:
                code_text += file.read().lower() + "\n"
        except Exception as e:
            pass
            
    if py_count == 0 and js_count == 0:
        print(f"Error: No Python (.py) or Node.js (.js) files found in '{path}'.")
        print("CloudPredict requires code files to analyze the runtime and workload.")
        sys.exit(1)
            
    runtime = 'nodejs' if js_count > py_count else 'python'
    workload = 'cpu_math_2_xs_v1' # default
    
    import re
    def has_kw(kw_list):
        return any(re.search(rf'\b{re.escape(kw)}\b', code_text) for kw in kw_list)
        
    # Priority 1: Heavy Database / Web Business Logic
    if has_kw(['boto3', 'dynamodb', 'pymongo', 'sql', 'mysql', 'postgres', 'sqlalchemy', 'django', 'flask', 'express', 'fastapi', 'spring', 'mongoose', 'sequelize', 'redis', 'cassandra', 'psycopg2', 'prisma', 'typeorm', 'knex', 'pg', 'sqlite3', 'mongodb', 'couchdb', 'mariadb', 'oracle', 'cosmosdb']):
        workload = 'web_biz_1_xs_v1'
    # Priority 2: Data Processing
    elif has_kw(['pandas', 'dataframe', 'csv', 'spark', 'hadoop', 'dask', 'pyspark', 'beautifulsoup', 'lxml', 'parquet', 'avro', 'openpyxl', 'xlrd', 'xml.etree', 'xml2js', 'cheerio', 'polars', 'pyarrow', 'dbt', 'airflow', 'luigi', 'celery']):
        workload = 'data_proc_1_xs_v1'
    # Priority 3: Cryptography
    elif has_kw(['hashlib', 'crypto', 'bcrypt', 'hmac', 'rsa', 'argon2', 'scrypt', 'pbkdf2', 'jwt', 'jsonwebtoken', 'pyjwt', 'cryptography', 'pycryptodome', 'tls', 'ssl', 'aes', 'des', 'sha256', 'md5']):
        workload = 'crypto_hash_xs_v1'
    # Priority 4: Network / External APIs
    elif has_kw(['request', 'http', 'axios', 'fetch', 'urllib', 'aiohttp', 'httpx', 'got', 'superagent', 'node-fetch', 'socket.io', 'websockets', 'grpc', 'graphql', 'apollo', 'xmlhttprequest', 'urllib3', 'curl']):
        workload = 'net_sim_1_xs_v1'
    # Priority 5: File I/O
    elif has_kw(['open', 'fs.read', 'fs.write', 'pathlib', 'shutil', 'os.path', 'fs-extra', 'fs.promises', 'stream', 'filereader', 'filewriter', 'tempfile', 'glob', 'tarfile', 'zipfile', 'fs.append', 'fs.unlink']):
        workload = 'file_io_xs_v1'
    # Priority 6: Basic JSON Transformation
    elif has_kw(['import json', 'require("json")', 'json.parse', 'json.dumps', 'json.stringify', 'ujson', 'orjson', 'simplejson', 'pydantic']):
        workload = 'json_transform_xs_v1'
    # Priority 7: CPU / Math operations
    elif has_kw(['numpy', 'math', 'scipy', 'scikit-learn', 'sklearn', 'tensorflow', 'pytorch', 'keras', 'statsmodels', 'numba', 'sympy', 'tensor', 'matrix', 'neural']):
        workload = 'cpu_math_2_xs_v1'
        
    return runtime, workload

def run_predict(args, models_dir):
    duration_model, cost_model, d_name, c_name = load_models(models_dir)
    
    df_features = create_feature_vector(
        args.platform, args.runtime, args.region, args.cold_start, args.input_size, args.workload
    )
    
    pred_duration = duration_model.predict(df_features)[0]
    pred_cost = cost_model.predict(df_features)[0]
    
    print("\n" + "=" * 55)
    print("  CloudPredict - Manual Forecaster ")
    print("=" * 55)
    print(f"  Configuration:")
    print(f"    - Platform   : {args.platform.upper()}")
    print(f"    - Runtime    : {args.runtime}")
    print(f"    - Region     : {args.region}")
    print(f"    - Cold Start : {'Yes' if args.cold_start else 'No'}")
    print(f"    - Input Size : {args.input_size}")
    print(f"    - Workload   : {args.workload}")
    print("-" * 55)
    print(f"  Predictions:")
    print(f"    - Expected Duration : {pred_duration:8.2f} ms")
    print(f"    - Expected Cost     : ${pred_cost:8.6f}")
    print("-" * 55)
    print(f"  Powered by: {d_name} (Latency) | {c_name} (Cost)")
    print("=" * 55 + "\n")

def run_analyze(args, models_dir):
    duration_model, cost_model, d_name, c_name = load_models(models_dir)
    
    print(f"\nAnalyzing project: {args.path}...")
    runtime, workload = analyze_project(args.path)
    
    print(f"Detected Runtime : {runtime}")
    print(f"Inferred Workload: {workload}")
    print("\nEvaluating across platforms (AWS, Azure, GCP)...\n")
    
    platforms = ['aws', 'azure', 'gcp']
    results = []
    
    for plat in platforms:
        # Evaluate Warm Start
        df_warm = create_feature_vector(plat, runtime, 'us-east-1', False, args.input_size, workload)
        warm_dur = duration_model.predict(df_warm)[0]
        warm_cost = cost_model.predict(df_warm)[0]
        
        # Evaluate Cold Start
        df_cold = create_feature_vector(plat, runtime, 'us-east-1', True, args.input_size, workload)
        cold_dur = duration_model.predict(df_cold)[0]
        
        results.append({
            'Platform': plat.upper(),
            'Duration (Warm)': warm_dur,
            'Duration (Cold)': cold_dur,
            'Cost per Exec': warm_cost
        })
        
    # Sort to find best
    fastest = min(results, key=lambda x: x['Duration (Warm)'])['Platform']
    cheapest = min(results, key=lambda x: x['Cost per Exec'])['Platform']
    
    print("=" * 75)
    print(f"{'Platform':<12} | {'Warm Duration':<15} | {'Cold Duration':<15} | {'Estimated Cost':<15}")
    print("-" * 75)
    for res in results:
        dur_warm_str = f"{res['Duration (Warm)']:.2f} ms"
        dur_cold_str = f"{res['Duration (Cold)']:.2f} ms"
        cost_str = f"${res['Cost per Exec']:.6f}"
        
        marker = ""
        if res['Platform'] == fastest: marker += " [FASTEST]"
        if res['Platform'] == cheapest: marker += " [CHEAPEST]"
            
        print(f"{res['Platform']:<12} | {dur_warm_str:<15} | {dur_cold_str:<15} | {cost_str:<15} {marker}")
    print("=" * 75)
    print(f"\nRecommendation: Deploy to {cheapest} for best cost, or {fastest} for best performance.\n")


def main():
    parser = argparse.ArgumentParser(
        description="CloudPredict CLI - Intelligent Serverless Decision Engine",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    subparsers = parser.add_subparsers(dest="command", required=True, help="Available commands")
    
    # Subcommand: Predict
    predict_parser = subparsers.add_parser("predict", help="Manually predict performance for a specific configuration")
    predict_parser.add_argument('--input-size', type=float, default=1024, help="Input size processed by the function")
    predict_parser.add_argument('--cold-start', action='store_true', help="Flag to simulate a cold start execution")
    predict_parser.add_argument('--platform', choices=['aws', 'azure', 'gcp'], default='aws', help="Cloud provider platform")
    predict_parser.add_argument('--runtime', choices=['python', 'nodejs', 'other'], default='python', help="Programming language runtime")
    predict_parser.add_argument('--region', choices=['us-east-1', 'us-central1', 'other'], default='us-east-1', help="Deployment region")
    predict_parser.add_argument('--workload', type=str, default='cpu_math_2_xs_v1', help="Type of workload")

    # Subcommand: Analyze
    analyze_parser = subparsers.add_parser("analyze", help="Analyze a script or project folder and recommend the best cloud platform")
    analyze_parser.add_argument('path', type=str, help="Path to the script file or project directory (e.g., . or app.py)")
    analyze_parser.add_argument('--input-size', type=float, default=1024, help="Expected average input size in KB")
    
    args = parser.parse_args()
    
    models_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'models')
    
    if args.command == "predict":
        run_predict(args, models_dir)
    elif args.command == "analyze":
        if not os.path.exists(args.path):
            print(f"Error: Path '{args.path}' does not exist.")
            sys.exit(1)
        run_analyze(args, models_dir)

if __name__ == '__main__':
    main()
